# Generated by Django 5.0.6 on 2024-09-02 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositeForm',
            fields=[
                ('transactions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transactions')),
            ],
            bases=('transactions.transactions',),
        ),
        migrations.CreateModel(
            name='LoanRequestForm',
            fields=[
                ('transactions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transactions')),
            ],
            bases=('transactions.transactions',),
        ),
        migrations.CreateModel(
            name='WithdrawForm',
            fields=[
                ('transactions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transactions')),
            ],
            bases=('transactions.transactions',),
        ),
    ]
