# Generated by Django 5.0.6 on 2024-09-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_depositeform_loanrequestform_withdrawform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequestform',
            name='transactions_ptr',
        ),
        migrations.RemoveField(
            model_name='withdrawform',
            name='transactions_ptr',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposite'), (2, 'Withdraw'), (3, 'Loan'), (4, 'Loan Paid')], null=True),
        ),
        migrations.DeleteModel(
            name='DepositeForm',
        ),
        migrations.DeleteModel(
            name='LoanRequestForm',
        ),
        migrations.DeleteModel(
            name='WithdrawForm',
        ),
    ]
