# Generated by Django 5.0.6 on 2024-09-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transactions_transaction_type_tranfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transfer_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.DeleteModel(
            name='Tranfer',
        ),
    ]
