# Generated by Django 5.0.6 on 2024-09-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transactions_transfer_money_delete_tranfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='account_no',
            field=models.IntegerField(default=0),
        ),
    ]
