# Generated by Django 5.0.6 on 2024-09-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transactions_account_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='account_no',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transfer_money',
            field=models.DecimalField(choices=[(1, 'Deposite'), (2, 'Withdraw'), (3, 'Loan'), (4, 'Loan Paid'), (5, 'Transfer')], decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
